/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CoreDexRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TIMELOCK_DELAY"
      | "contracts"
      | "executeUpdate"
      | "governance"
      | "pause"
      | "paused"
      | "pendingUpdates"
      | "proposeUpdate"
      | "register"
      | "resolve"
      | "transferGovernance"
      | "unpause"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ContractUpdated"
      | "ProtocolPaused"
      | "ProtocolUnpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "TIMELOCK_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contracts",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeUpdate",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingUpdates",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeUpdate",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "resolve", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transferGovernance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "TIMELOCK_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contracts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingUpdates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "resolve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace ContractUpdatedEvent {
  export type InputTuple = [
    key: BytesLike,
    oldAddress: AddressLike,
    newAddress: AddressLike,
    version: BigNumberish
  ];
  export type OutputTuple = [
    key: string,
    oldAddress: string,
    newAddress: string,
    version: bigint
  ];
  export interface OutputObject {
    key: string;
    oldAddress: string;
    newAddress: string;
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolPausedEvent {
  export type InputTuple = [pauser: AddressLike];
  export type OutputTuple = [pauser: string];
  export interface OutputObject {
    pauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolUnpausedEvent {
  export type InputTuple = [unpauser: AddressLike];
  export type OutputTuple = [unpauser: string];
  export interface OutputObject {
    unpauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CoreDexRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CoreDexRegistry;
  waitForDeployment(): Promise<this>;

  interface: CoreDexRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TIMELOCK_DELAY: TypedContractMethod<[], [bigint], "view">;

  contracts: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  executeUpdate: TypedContractMethod<[key: BytesLike], [void], "nonpayable">;

  governance: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingUpdates: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, boolean] & {
        newAddress: string;
        activationBlock: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  proposeUpdate: TypedContractMethod<
    [key: BytesLike, impl: AddressLike],
    [void],
    "nonpayable"
  >;

  register: TypedContractMethod<
    [key: BytesLike, impl: AddressLike],
    [void],
    "nonpayable"
  >;

  resolve: TypedContractMethod<[key: BytesLike], [string], "view">;

  transferGovernance: TypedContractMethod<
    [newGovernance: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TIMELOCK_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "contracts"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "executeUpdate"
  ): TypedContractMethod<[key: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "governance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingUpdates"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, bigint, boolean] & {
        newAddress: string;
        activationBlock: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposeUpdate"
  ): TypedContractMethod<
    [key: BytesLike, impl: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [key: BytesLike, impl: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolve"
  ): TypedContractMethod<[key: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "transferGovernance"
  ): TypedContractMethod<[newGovernance: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "ContractUpdated"
  ): TypedContractEvent<
    ContractUpdatedEvent.InputTuple,
    ContractUpdatedEvent.OutputTuple,
    ContractUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolPaused"
  ): TypedContractEvent<
    ProtocolPausedEvent.InputTuple,
    ProtocolPausedEvent.OutputTuple,
    ProtocolPausedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolUnpaused"
  ): TypedContractEvent<
    ProtocolUnpausedEvent.InputTuple,
    ProtocolUnpausedEvent.OutputTuple,
    ProtocolUnpausedEvent.OutputObject
  >;

  filters: {
    "ContractUpdated(bytes32,address,address,uint32)": TypedContractEvent<
      ContractUpdatedEvent.InputTuple,
      ContractUpdatedEvent.OutputTuple,
      ContractUpdatedEvent.OutputObject
    >;
    ContractUpdated: TypedContractEvent<
      ContractUpdatedEvent.InputTuple,
      ContractUpdatedEvent.OutputTuple,
      ContractUpdatedEvent.OutputObject
    >;

    "ProtocolPaused(address)": TypedContractEvent<
      ProtocolPausedEvent.InputTuple,
      ProtocolPausedEvent.OutputTuple,
      ProtocolPausedEvent.OutputObject
    >;
    ProtocolPaused: TypedContractEvent<
      ProtocolPausedEvent.InputTuple,
      ProtocolPausedEvent.OutputTuple,
      ProtocolPausedEvent.OutputObject
    >;

    "ProtocolUnpaused(address)": TypedContractEvent<
      ProtocolUnpausedEvent.InputTuple,
      ProtocolUnpausedEvent.OutputTuple,
      ProtocolUnpausedEvent.OutputObject
    >;
    ProtocolUnpaused: TypedContractEvent<
      ProtocolUnpausedEvent.InputTuple,
      ProtocolUnpausedEvent.OutputTuple,
      ProtocolUnpausedEvent.OutputObject
    >;
  };
}
