/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface CoretimeLedgerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FORWARD_POSITION"
      | "KEY_FORWARD_MARKET"
      | "KEY_OPTIONS_ENGINE"
      | "KEY_SETTLEMENT"
      | "KEY_YIELD_VAULT"
      | "OPTION_POSITION"
      | "VAULT_POSITION"
      | "addMargin"
      | "decrementPositionCount"
      | "getRegionLocker"
      | "incrementPositionCount"
      | "isRegionLocked"
      | "lockRegion"
      | "marginBalance"
      | "openPositionCount"
      | "regionLocked"
      | "regionLockedBy"
      | "regionPositionType"
      | "registry"
      | "releaseMargin"
      | "totalLockEvents"
      | "unlockRegion"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MarginUpdated" | "RegionLocked" | "RegionUnlocked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "FORWARD_POSITION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEY_FORWARD_MARKET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEY_OPTIONS_ENGINE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEY_SETTLEMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEY_YIELD_VAULT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPTION_POSITION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VAULT_POSITION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addMargin",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decrementPositionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegionLocker",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "incrementPositionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegionLocked",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockRegion",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "marginBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "openPositionCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "regionLocked",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "regionLockedBy",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "regionPositionType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "releaseMargin",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalLockEvents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "unlockRegion",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "FORWARD_POSITION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KEY_FORWARD_MARKET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KEY_OPTIONS_ENGINE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KEY_SETTLEMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KEY_YIELD_VAULT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPTION_POSITION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VAULT_POSITION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addMargin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decrementPositionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegionLocker",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incrementPositionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegionLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lockRegion", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "marginBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openPositionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "regionLocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "regionLockedBy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "regionPositionType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseMargin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLockEvents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockRegion",
    data: BytesLike
  ): Result;
}

export namespace MarginUpdatedEvent {
  export type InputTuple = [account: AddressLike, newBalance: BigNumberish];
  export type OutputTuple = [account: string, newBalance: bigint];
  export interface OutputObject {
    account: string;
    newBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegionLockedEvent {
  export type InputTuple = [
    regionId: BigNumberish,
    lockedBy: AddressLike,
    positionType: BytesLike
  ];
  export type OutputTuple = [
    regionId: bigint,
    lockedBy: string,
    positionType: string
  ];
  export interface OutputObject {
    regionId: bigint;
    lockedBy: string;
    positionType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegionUnlockedEvent {
  export type InputTuple = [regionId: BigNumberish, unlockedBy: AddressLike];
  export type OutputTuple = [regionId: bigint, unlockedBy: string];
  export interface OutputObject {
    regionId: bigint;
    unlockedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CoretimeLedger extends BaseContract {
  connect(runner?: ContractRunner | null): CoretimeLedger;
  waitForDeployment(): Promise<this>;

  interface: CoretimeLedgerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FORWARD_POSITION: TypedContractMethod<[], [string], "view">;

  KEY_FORWARD_MARKET: TypedContractMethod<[], [string], "view">;

  KEY_OPTIONS_ENGINE: TypedContractMethod<[], [string], "view">;

  KEY_SETTLEMENT: TypedContractMethod<[], [string], "view">;

  KEY_YIELD_VAULT: TypedContractMethod<[], [string], "view">;

  OPTION_POSITION: TypedContractMethod<[], [string], "view">;

  VAULT_POSITION: TypedContractMethod<[], [string], "view">;

  addMargin: TypedContractMethod<
    [account: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  decrementPositionCount: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  getRegionLocker: TypedContractMethod<
    [regionId: BigNumberish],
    [string],
    "view"
  >;

  incrementPositionCount: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  isRegionLocked: TypedContractMethod<
    [regionId: BigNumberish],
    [boolean],
    "view"
  >;

  lockRegion: TypedContractMethod<
    [regionId: BigNumberish, positionType: BytesLike],
    [void],
    "nonpayable"
  >;

  marginBalance: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  openPositionCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  regionLocked: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  regionLockedBy: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  regionPositionType: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  releaseMargin: TypedContractMethod<
    [account: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalLockEvents: TypedContractMethod<[], [bigint], "view">;

  unlockRegion: TypedContractMethod<
    [regionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FORWARD_POSITION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEY_FORWARD_MARKET"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEY_OPTIONS_ENGINE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEY_SETTLEMENT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEY_YIELD_VAULT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPTION_POSITION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VAULT_POSITION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addMargin"
  ): TypedContractMethod<
    [account: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decrementPositionCount"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getRegionLocker"
  ): TypedContractMethod<[regionId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "incrementPositionCount"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isRegionLocked"
  ): TypedContractMethod<[regionId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "lockRegion"
  ): TypedContractMethod<
    [regionId: BigNumberish, positionType: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "marginBalance"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "openPositionCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "regionLocked"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "regionLockedBy"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "regionPositionType"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "releaseMargin"
  ): TypedContractMethod<
    [account: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalLockEvents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unlockRegion"
  ): TypedContractMethod<[regionId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "MarginUpdated"
  ): TypedContractEvent<
    MarginUpdatedEvent.InputTuple,
    MarginUpdatedEvent.OutputTuple,
    MarginUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RegionLocked"
  ): TypedContractEvent<
    RegionLockedEvent.InputTuple,
    RegionLockedEvent.OutputTuple,
    RegionLockedEvent.OutputObject
  >;
  getEvent(
    key: "RegionUnlocked"
  ): TypedContractEvent<
    RegionUnlockedEvent.InputTuple,
    RegionUnlockedEvent.OutputTuple,
    RegionUnlockedEvent.OutputObject
  >;

  filters: {
    "MarginUpdated(address,uint256)": TypedContractEvent<
      MarginUpdatedEvent.InputTuple,
      MarginUpdatedEvent.OutputTuple,
      MarginUpdatedEvent.OutputObject
    >;
    MarginUpdated: TypedContractEvent<
      MarginUpdatedEvent.InputTuple,
      MarginUpdatedEvent.OutputTuple,
      MarginUpdatedEvent.OutputObject
    >;

    "RegionLocked(uint128,address,bytes32)": TypedContractEvent<
      RegionLockedEvent.InputTuple,
      RegionLockedEvent.OutputTuple,
      RegionLockedEvent.OutputObject
    >;
    RegionLocked: TypedContractEvent<
      RegionLockedEvent.InputTuple,
      RegionLockedEvent.OutputTuple,
      RegionLockedEvent.OutputObject
    >;

    "RegionUnlocked(uint128,address)": TypedContractEvent<
      RegionUnlockedEvent.InputTuple,
      RegionUnlockedEvent.OutputTuple,
      RegionUnlockedEvent.OutputObject
    >;
    RegionUnlocked: TypedContractEvent<
      RegionUnlockedEvent.InputTuple,
      RegionUnlockedEvent.OutputTuple,
      RegionUnlockedEvent.OutputObject
    >;
  };
}
