/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ForwardMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ASSETS_PRECOMPILE"
      | "GRACE_PERIOD"
      | "KEY_CORETIME_ORACLE"
      | "KEY_LEDGER"
      | "KEY_SETTLEMENT"
      | "PRICE_BAND_PCT"
      | "buyerOrders"
      | "cancel"
      | "coretimeNFT"
      | "createAsk"
      | "expireOrder"
      | "getBuyerOrders"
      | "getRegionOrder"
      | "getSellerOrders"
      | "matchOrder"
      | "nextOrderId"
      | "orders"
      | "regionToOrder"
      | "registry"
      | "sellerOrders"
      | "settle"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OrderCancelled"
      | "OrderCreated"
      | "OrderExpired"
      | "OrderMatched"
      | "OrderSettled"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ASSETS_PRECOMPILE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GRACE_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEY_CORETIME_ORACLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEY_LEDGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEY_SETTLEMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_BAND_PCT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyerOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "coretimeNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createAsk",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "expireOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBuyerOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRegionOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSellerOrders",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "matchOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextOrderId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orders",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "regionToOrder",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sellerOrders",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settle",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ASSETS_PRECOMPILE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GRACE_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KEY_CORETIME_ORACLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "KEY_LEDGER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "KEY_SETTLEMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_BAND_PCT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buyerOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "coretimeNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createAsk", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "expireOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBuyerOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRegionOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSellerOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "matchOrder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextOrderId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "orders", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "regionToOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellerOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settle", data: BytesLike): Result;
}

export namespace OrderCancelledEvent {
  export type InputTuple = [orderId: BigNumberish, cancelledBy: AddressLike];
  export type OutputTuple = [orderId: bigint, cancelledBy: string];
  export interface OutputObject {
    orderId: bigint;
    cancelledBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    seller: AddressLike,
    regionId: BigNumberish,
    strikePriceDOT: BigNumberish,
    deliveryBlock: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    seller: string,
    regionId: bigint,
    strikePriceDOT: bigint,
    deliveryBlock: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    seller: string;
    regionId: bigint;
    strikePriceDOT: bigint;
    deliveryBlock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderExpiredEvent {
  export type InputTuple = [orderId: BigNumberish];
  export type OutputTuple = [orderId: bigint];
  export interface OutputObject {
    orderId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderMatchedEvent {
  export type InputTuple = [orderId: BigNumberish, buyer: AddressLike];
  export type OutputTuple = [orderId: bigint, buyer: string];
  export interface OutputObject {
    orderId: bigint;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderSettledEvent {
  export type InputTuple = [orderId: BigNumberish, success: boolean];
  export type OutputTuple = [orderId: bigint, success: boolean];
  export interface OutputObject {
    orderId: bigint;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ForwardMarket extends BaseContract {
  connect(runner?: ContractRunner | null): ForwardMarket;
  waitForDeployment(): Promise<this>;

  interface: ForwardMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ASSETS_PRECOMPILE: TypedContractMethod<[], [string], "view">;

  GRACE_PERIOD: TypedContractMethod<[], [bigint], "view">;

  KEY_CORETIME_ORACLE: TypedContractMethod<[], [string], "view">;

  KEY_LEDGER: TypedContractMethod<[], [string], "view">;

  KEY_SETTLEMENT: TypedContractMethod<[], [string], "view">;

  PRICE_BAND_PCT: TypedContractMethod<[], [bigint], "view">;

  buyerOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  cancel: TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;

  coretimeNFT: TypedContractMethod<[], [string], "view">;

  createAsk: TypedContractMethod<
    [
      regionId: BigNumberish,
      strikePrice: BigNumberish,
      deliveryBlock: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  expireOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBuyerOrders: TypedContractMethod<[buyer: AddressLike], [bigint[]], "view">;

  getRegionOrder: TypedContractMethod<
    [regionId: BigNumberish],
    [bigint],
    "view"
  >;

  getSellerOrders: TypedContractMethod<
    [seller: AddressLike],
    [bigint[]],
    "view"
  >;

  matchOrder: TypedContractMethod<
    [orderId: BigNumberish],
    [void],
    "nonpayable"
  >;

  nextOrderId: TypedContractMethod<[], [bigint], "view">;

  orders: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, bigint] & {
        orderId: bigint;
        seller: string;
        buyer: string;
        coretimeRegion: bigint;
        strikePriceDOT: bigint;
        deliveryBlock: bigint;
        createdBlock: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  regionToOrder: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  sellerOrders: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  settle: TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ASSETS_PRECOMPILE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "GRACE_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "KEY_CORETIME_ORACLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEY_LEDGER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEY_SETTLEMENT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PRICE_BAND_PCT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyerOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "coretimeNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createAsk"
  ): TypedContractMethod<
    [
      regionId: BigNumberish,
      strikePrice: BigNumberish,
      deliveryBlock: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "expireOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBuyerOrders"
  ): TypedContractMethod<[buyer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRegionOrder"
  ): TypedContractMethod<[regionId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSellerOrders"
  ): TypedContractMethod<[seller: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "matchOrder"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nextOrderId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orders"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, bigint, bigint] & {
        orderId: bigint;
        seller: string;
        buyer: string;
        coretimeRegion: bigint;
        strikePriceDOT: bigint;
        deliveryBlock: bigint;
        createdBlock: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "regionToOrder"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "sellerOrders"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "settle"
  ): TypedContractMethod<[orderId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "OrderCancelled"
  ): TypedContractEvent<
    OrderCancelledEvent.InputTuple,
    OrderCancelledEvent.OutputTuple,
    OrderCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderExpired"
  ): TypedContractEvent<
    OrderExpiredEvent.InputTuple,
    OrderExpiredEvent.OutputTuple,
    OrderExpiredEvent.OutputObject
  >;
  getEvent(
    key: "OrderMatched"
  ): TypedContractEvent<
    OrderMatchedEvent.InputTuple,
    OrderMatchedEvent.OutputTuple,
    OrderMatchedEvent.OutputObject
  >;
  getEvent(
    key: "OrderSettled"
  ): TypedContractEvent<
    OrderSettledEvent.InputTuple,
    OrderSettledEvent.OutputTuple,
    OrderSettledEvent.OutputObject
  >;

  filters: {
    "OrderCancelled(uint256,address)": TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;
    OrderCancelled: TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;

    "OrderCreated(uint256,address,uint128,uint128,uint32)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderExpired(uint256)": TypedContractEvent<
      OrderExpiredEvent.InputTuple,
      OrderExpiredEvent.OutputTuple,
      OrderExpiredEvent.OutputObject
    >;
    OrderExpired: TypedContractEvent<
      OrderExpiredEvent.InputTuple,
      OrderExpiredEvent.OutputTuple,
      OrderExpiredEvent.OutputObject
    >;

    "OrderMatched(uint256,address)": TypedContractEvent<
      OrderMatchedEvent.InputTuple,
      OrderMatchedEvent.OutputTuple,
      OrderMatchedEvent.OutputObject
    >;
    OrderMatched: TypedContractEvent<
      OrderMatchedEvent.InputTuple,
      OrderMatchedEvent.OutputTuple,
      OrderMatchedEvent.OutputObject
    >;

    "OrderSettled(uint256,bool)": TypedContractEvent<
      OrderSettledEvent.InputTuple,
      OrderSettledEvent.OutputTuple,
      OrderSettledEvent.OutputObject
    >;
    OrderSettled: TypedContractEvent<
      OrderSettledEvent.InputTuple,
      OrderSettledEvent.OutputTuple,
      OrderSettledEvent.OutputObject
    >;
  };
}
