/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "CoreDexRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CoreDexRegistry__factory>;
    getContractFactory(
      name: "CoretimeLedger",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CoretimeLedger__factory>;
    getContractFactory(
      name: "ForwardMarket",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ForwardMarket__factory>;
    getContractFactory(
      name: "IAssetsPrecompile",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAssetsPrecompile__factory>;
    getContractFactory(
      name: "ICoreDexRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICoreDexRegistry__factory>;
    getContractFactory(
      name: "ICoretimeNFT",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICoretimeNFT__factory>;
    getContractFactory(
      name: "IXcmPrecompile",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IXcmPrecompile__factory>;
    getContractFactory(
      name: "Errors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Errors__factory>;
    getContractFactory(
      name: "Events",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Events__factory>;
    getContractFactory(
      name: "OptionsEngine",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OptionsEngine__factory>;
    getContractFactory(
      name: "SettlementExecutor",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SettlementExecutor__factory>;
    getContractFactory(
      name: "YieldVault",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.YieldVault__factory>;

    getContractAt(
      name: "CoreDexRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CoreDexRegistry>;
    getContractAt(
      name: "CoretimeLedger",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CoretimeLedger>;
    getContractAt(
      name: "ForwardMarket",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ForwardMarket>;
    getContractAt(
      name: "IAssetsPrecompile",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAssetsPrecompile>;
    getContractAt(
      name: "ICoreDexRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICoreDexRegistry>;
    getContractAt(
      name: "ICoretimeNFT",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ICoretimeNFT>;
    getContractAt(
      name: "IXcmPrecompile",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IXcmPrecompile>;
    getContractAt(
      name: "Errors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Errors>;
    getContractAt(
      name: "Events",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Events>;
    getContractAt(
      name: "OptionsEngine",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.OptionsEngine>;
    getContractAt(
      name: "SettlementExecutor",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SettlementExecutor>;
    getContractAt(
      name: "YieldVault",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.YieldVault>;

    deployContract(
      name: "CoreDexRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CoreDexRegistry>;
    deployContract(
      name: "CoretimeLedger",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CoretimeLedger>;
    deployContract(
      name: "ForwardMarket",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ForwardMarket>;
    deployContract(
      name: "IAssetsPrecompile",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAssetsPrecompile>;
    deployContract(
      name: "ICoreDexRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICoreDexRegistry>;
    deployContract(
      name: "ICoretimeNFT",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICoretimeNFT>;
    deployContract(
      name: "IXcmPrecompile",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IXcmPrecompile>;
    deployContract(
      name: "Errors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Errors>;
    deployContract(
      name: "Events",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Events>;
    deployContract(
      name: "OptionsEngine",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OptionsEngine>;
    deployContract(
      name: "SettlementExecutor",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SettlementExecutor>;
    deployContract(
      name: "YieldVault",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YieldVault>;

    deployContract(
      name: "CoreDexRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CoreDexRegistry>;
    deployContract(
      name: "CoretimeLedger",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CoretimeLedger>;
    deployContract(
      name: "ForwardMarket",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ForwardMarket>;
    deployContract(
      name: "IAssetsPrecompile",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAssetsPrecompile>;
    deployContract(
      name: "ICoreDexRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICoreDexRegistry>;
    deployContract(
      name: "ICoretimeNFT",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ICoretimeNFT>;
    deployContract(
      name: "IXcmPrecompile",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IXcmPrecompile>;
    deployContract(
      name: "Errors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Errors>;
    deployContract(
      name: "Events",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Events>;
    deployContract(
      name: "OptionsEngine",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.OptionsEngine>;
    deployContract(
      name: "SettlementExecutor",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SettlementExecutor>;
    deployContract(
      name: "YieldVault",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.YieldVault>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
