/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface OptionsEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ASSETS_PRECOMPILE"
      | "KEY_CORETIME_ORACLE"
      | "KEY_LEDGER"
      | "KEY_PRICING_MODULE"
      | "KEY_SETTLEMENT"
      | "OPTION_CALL"
      | "OPTION_PUT"
      | "buyOption"
      | "coretimeNFT"
      | "exercise"
      | "expireOption"
      | "getHolderOptions"
      | "getWriterOptions"
      | "holderOptions"
      | "nextOptionId"
      | "options"
      | "registry"
      | "writeCall"
      | "writePut"
      | "writerOptions"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OptionExercised"
      | "OptionExpired"
      | "OptionPurchased"
      | "OptionWritten"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ASSETS_PRECOMPILE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEY_CORETIME_ORACLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEY_LEDGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEY_PRICING_MODULE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEY_SETTLEMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPTION_CALL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OPTION_PUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyOption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "coretimeNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "exercise",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "expireOption",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHolderOptions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getWriterOptions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "holderOptions",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextOptionId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "options",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "writeCall",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "writePut",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "writerOptions",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ASSETS_PRECOMPILE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KEY_CORETIME_ORACLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "KEY_LEDGER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "KEY_PRICING_MODULE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KEY_SETTLEMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OPTION_CALL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "OPTION_PUT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyOption", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "coretimeNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "exercise", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "expireOption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHolderOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWriterOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "holderOptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextOptionId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "options", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "writeCall", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "writePut", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "writerOptions",
    data: BytesLike
  ): Result;
}

export namespace OptionExercisedEvent {
  export type InputTuple = [optionId: BigNumberish, holder: AddressLike];
  export type OutputTuple = [optionId: bigint, holder: string];
  export interface OutputObject {
    optionId: bigint;
    holder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OptionExpiredEvent {
  export type InputTuple = [optionId: BigNumberish];
  export type OutputTuple = [optionId: bigint];
  export interface OutputObject {
    optionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OptionPurchasedEvent {
  export type InputTuple = [optionId: BigNumberish, holder: AddressLike];
  export type OutputTuple = [optionId: bigint, holder: string];
  export interface OutputObject {
    optionId: bigint;
    holder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OptionWrittenEvent {
  export type InputTuple = [
    optionId: BigNumberish,
    writer: AddressLike,
    optionType: BigNumberish,
    premium: BigNumberish
  ];
  export type OutputTuple = [
    optionId: bigint,
    writer: string,
    optionType: bigint,
    premium: bigint
  ];
  export interface OutputObject {
    optionId: bigint;
    writer: string;
    optionType: bigint;
    premium: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OptionsEngine extends BaseContract {
  connect(runner?: ContractRunner | null): OptionsEngine;
  waitForDeployment(): Promise<this>;

  interface: OptionsEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ASSETS_PRECOMPILE: TypedContractMethod<[], [string], "view">;

  KEY_CORETIME_ORACLE: TypedContractMethod<[], [string], "view">;

  KEY_LEDGER: TypedContractMethod<[], [string], "view">;

  KEY_PRICING_MODULE: TypedContractMethod<[], [string], "view">;

  KEY_SETTLEMENT: TypedContractMethod<[], [string], "view">;

  OPTION_CALL: TypedContractMethod<[], [bigint], "view">;

  OPTION_PUT: TypedContractMethod<[], [bigint], "view">;

  buyOption: TypedContractMethod<
    [optionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  coretimeNFT: TypedContractMethod<[], [string], "view">;

  exercise: TypedContractMethod<[optionId: BigNumberish], [void], "nonpayable">;

  expireOption: TypedContractMethod<
    [optionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getHolderOptions: TypedContractMethod<
    [holder: AddressLike],
    [bigint[]],
    "view"
  >;

  getWriterOptions: TypedContractMethod<
    [writer: AddressLike],
    [bigint[]],
    "view"
  >;

  holderOptions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  nextOptionId: TypedContractMethod<[], [bigint], "view">;

  options: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        optionId: bigint;
        writer: string;
        holder: string;
        coretimeRegion: bigint;
        strikePriceDOT: bigint;
        premiumDOT: bigint;
        expiryBlock: bigint;
        optionType: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  writeCall: TypedContractMethod<
    [regionId: BigNumberish, strike: BigNumberish, expiryBlock: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  writePut: TypedContractMethod<
    [regionId: BigNumberish, strike: BigNumberish, expiryBlock: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  writerOptions: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ASSETS_PRECOMPILE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEY_CORETIME_ORACLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEY_LEDGER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEY_PRICING_MODULE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEY_SETTLEMENT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OPTION_CALL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OPTION_PUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyOption"
  ): TypedContractMethod<[optionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "coretimeNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "exercise"
  ): TypedContractMethod<[optionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "expireOption"
  ): TypedContractMethod<[optionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getHolderOptions"
  ): TypedContractMethod<[holder: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getWriterOptions"
  ): TypedContractMethod<[writer: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "holderOptions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextOptionId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "options"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        optionId: bigint;
        writer: string;
        holder: string;
        coretimeRegion: bigint;
        strikePriceDOT: bigint;
        premiumDOT: bigint;
        expiryBlock: bigint;
        optionType: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "writeCall"
  ): TypedContractMethod<
    [regionId: BigNumberish, strike: BigNumberish, expiryBlock: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "writePut"
  ): TypedContractMethod<
    [regionId: BigNumberish, strike: BigNumberish, expiryBlock: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "writerOptions"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "OptionExercised"
  ): TypedContractEvent<
    OptionExercisedEvent.InputTuple,
    OptionExercisedEvent.OutputTuple,
    OptionExercisedEvent.OutputObject
  >;
  getEvent(
    key: "OptionExpired"
  ): TypedContractEvent<
    OptionExpiredEvent.InputTuple,
    OptionExpiredEvent.OutputTuple,
    OptionExpiredEvent.OutputObject
  >;
  getEvent(
    key: "OptionPurchased"
  ): TypedContractEvent<
    OptionPurchasedEvent.InputTuple,
    OptionPurchasedEvent.OutputTuple,
    OptionPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "OptionWritten"
  ): TypedContractEvent<
    OptionWrittenEvent.InputTuple,
    OptionWrittenEvent.OutputTuple,
    OptionWrittenEvent.OutputObject
  >;

  filters: {
    "OptionExercised(uint256,address)": TypedContractEvent<
      OptionExercisedEvent.InputTuple,
      OptionExercisedEvent.OutputTuple,
      OptionExercisedEvent.OutputObject
    >;
    OptionExercised: TypedContractEvent<
      OptionExercisedEvent.InputTuple,
      OptionExercisedEvent.OutputTuple,
      OptionExercisedEvent.OutputObject
    >;

    "OptionExpired(uint256)": TypedContractEvent<
      OptionExpiredEvent.InputTuple,
      OptionExpiredEvent.OutputTuple,
      OptionExpiredEvent.OutputObject
    >;
    OptionExpired: TypedContractEvent<
      OptionExpiredEvent.InputTuple,
      OptionExpiredEvent.OutputTuple,
      OptionExpiredEvent.OutputObject
    >;

    "OptionPurchased(uint256,address)": TypedContractEvent<
      OptionPurchasedEvent.InputTuple,
      OptionPurchasedEvent.OutputTuple,
      OptionPurchasedEvent.OutputObject
    >;
    OptionPurchased: TypedContractEvent<
      OptionPurchasedEvent.InputTuple,
      OptionPurchasedEvent.OutputTuple,
      OptionPurchasedEvent.OutputObject
    >;

    "OptionWritten(uint256,address,uint8,uint128)": TypedContractEvent<
      OptionWrittenEvent.InputTuple,
      OptionWrittenEvent.OutputTuple,
      OptionWrittenEvent.OutputObject
    >;
    OptionWritten: TypedContractEvent<
      OptionWrittenEvent.InputTuple,
      OptionWrittenEvent.OutputTuple,
      OptionWrittenEvent.OutputObject
    >;
  };
}
