/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SettlementExecutor {
  export type SettlementStruct = {
    positionId: BigNumberish;
    settlementType: BigNumberish;
    phase: BigNumberish;
    seller: AddressLike;
    buyer: AddressLike;
    regionId: BigNumberish;
    dotAmount: BigNumberish;
    xcmHash: BytesLike;
    dispatchBlock: BigNumberish;
    confirmBlock: BigNumberish;
  };

  export type SettlementStructOutput = [
    positionId: bigint,
    settlementType: bigint,
    phase: bigint,
    seller: string,
    buyer: string,
    regionId: bigint,
    dotAmount: bigint,
    xcmHash: string,
    dispatchBlock: bigint,
    confirmBlock: bigint
  ] & {
    positionId: bigint;
    settlementType: bigint;
    phase: bigint;
    seller: string;
    buyer: string;
    regionId: bigint;
    dotAmount: bigint;
    xcmHash: string;
    dispatchBlock: bigint;
    confirmBlock: bigint;
  };
}

export interface SettlementExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ASSETS_PRECOMPILE"
      | "ASSET_HUB_PARA_ID"
      | "CORETIME_PARA_ID"
      | "DEFAULT_PROOF_SIZE"
      | "DEFAULT_REF_TIME"
      | "KEY_FORWARD_MARKET"
      | "KEY_LEDGER"
      | "KEY_OPTIONS_ENGINE"
      | "RECOVERY_TIMEOUT"
      | "XCM_PRECOMPILE"
      | "coretimeNFT"
      | "getSettlement"
      | "handleSettlementCallback"
      | "isRecoverable"
      | "recoverFailed"
      | "registry"
      | "settleForward"
      | "settleOption"
      | "settlements"
      | "totalSettlements"
      | "xcmHashToPosition"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RecoveryInitiated"
      | "SettlementConfirmed"
      | "SettlementDispatched"
      | "SettlementFailed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ASSETS_PRECOMPILE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ASSET_HUB_PARA_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CORETIME_PARA_ID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_PROOF_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_REF_TIME",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEY_FORWARD_MARKET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEY_LEDGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEY_OPTIONS_ENGINE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RECOVERY_TIMEOUT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "XCM_PRECOMPILE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "coretimeNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSettlement",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "handleSettlementCallback",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "isRecoverable",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverFailed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "settleForward",
    values: [BigNumberish, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleOption",
    values: [BigNumberish, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settlements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSettlements",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "xcmHashToPosition",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ASSETS_PRECOMPILE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ASSET_HUB_PARA_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CORETIME_PARA_ID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_PROOF_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_REF_TIME",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "KEY_FORWARD_MARKET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "KEY_LEDGER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "KEY_OPTIONS_ENGINE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RECOVERY_TIMEOUT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "XCM_PRECOMPILE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "coretimeNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleSettlementCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRecoverable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverFailed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "settleForward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleOption",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settlements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSettlements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xcmHashToPosition",
    data: BytesLike
  ): Result;
}

export namespace RecoveryInitiatedEvent {
  export type InputTuple = [positionId: BigNumberish, initiator: AddressLike];
  export type OutputTuple = [positionId: bigint, initiator: string];
  export interface OutputObject {
    positionId: bigint;
    initiator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementConfirmedEvent {
  export type InputTuple = [positionId: BigNumberish, xcmHash: BytesLike];
  export type OutputTuple = [positionId: bigint, xcmHash: string];
  export interface OutputObject {
    positionId: bigint;
    xcmHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementDispatchedEvent {
  export type InputTuple = [positionId: BigNumberish, xcmHash: BytesLike];
  export type OutputTuple = [positionId: bigint, xcmHash: string];
  export interface OutputObject {
    positionId: bigint;
    xcmHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementFailedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    xcmHash: BytesLike,
    reason: BytesLike
  ];
  export type OutputTuple = [
    positionId: bigint,
    xcmHash: string,
    reason: string
  ];
  export interface OutputObject {
    positionId: bigint;
    xcmHash: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SettlementExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): SettlementExecutor;
  waitForDeployment(): Promise<this>;

  interface: SettlementExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ASSETS_PRECOMPILE: TypedContractMethod<[], [string], "view">;

  ASSET_HUB_PARA_ID: TypedContractMethod<[], [bigint], "view">;

  CORETIME_PARA_ID: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_PROOF_SIZE: TypedContractMethod<[], [bigint], "view">;

  DEFAULT_REF_TIME: TypedContractMethod<[], [bigint], "view">;

  KEY_FORWARD_MARKET: TypedContractMethod<[], [string], "view">;

  KEY_LEDGER: TypedContractMethod<[], [string], "view">;

  KEY_OPTIONS_ENGINE: TypedContractMethod<[], [string], "view">;

  RECOVERY_TIMEOUT: TypedContractMethod<[], [bigint], "view">;

  XCM_PRECOMPILE: TypedContractMethod<[], [string], "view">;

  coretimeNFT: TypedContractMethod<[], [string], "view">;

  getSettlement: TypedContractMethod<
    [positionId: BigNumberish],
    [SettlementExecutor.SettlementStructOutput],
    "view"
  >;

  handleSettlementCallback: TypedContractMethod<
    [xcmHash: BytesLike, success: boolean],
    [void],
    "nonpayable"
  >;

  isRecoverable: TypedContractMethod<
    [positionId: BigNumberish],
    [boolean],
    "view"
  >;

  recoverFailed: TypedContractMethod<
    [positionId: BigNumberish],
    [void],
    "nonpayable"
  >;

  registry: TypedContractMethod<[], [string], "view">;

  settleForward: TypedContractMethod<
    [
      orderId: BigNumberish,
      seller: AddressLike,
      buyer: AddressLike,
      regionId: BigNumberish,
      dotAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  settleOption: TypedContractMethod<
    [
      optionId: BigNumberish,
      seller: AddressLike,
      buyer: AddressLike,
      regionId: BigNumberish,
      dotAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  settlements: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        positionId: bigint;
        settlementType: bigint;
        phase: bigint;
        seller: string;
        buyer: string;
        regionId: bigint;
        dotAmount: bigint;
        xcmHash: string;
        dispatchBlock: bigint;
        confirmBlock: bigint;
      }
    ],
    "view"
  >;

  totalSettlements: TypedContractMethod<[], [bigint], "view">;

  xcmHashToPosition: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ASSETS_PRECOMPILE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ASSET_HUB_PARA_ID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "CORETIME_PARA_ID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_PROOF_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_REF_TIME"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "KEY_FORWARD_MARKET"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEY_LEDGER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "KEY_OPTIONS_ENGINE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RECOVERY_TIMEOUT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "XCM_PRECOMPILE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "coretimeNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSettlement"
  ): TypedContractMethod<
    [positionId: BigNumberish],
    [SettlementExecutor.SettlementStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "handleSettlementCallback"
  ): TypedContractMethod<
    [xcmHash: BytesLike, success: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isRecoverable"
  ): TypedContractMethod<[positionId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "recoverFailed"
  ): TypedContractMethod<[positionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "settleForward"
  ): TypedContractMethod<
    [
      orderId: BigNumberish,
      seller: AddressLike,
      buyer: AddressLike,
      regionId: BigNumberish,
      dotAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settleOption"
  ): TypedContractMethod<
    [
      optionId: BigNumberish,
      seller: AddressLike,
      buyer: AddressLike,
      regionId: BigNumberish,
      dotAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settlements"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint
      ] & {
        positionId: bigint;
        settlementType: bigint;
        phase: bigint;
        seller: string;
        buyer: string;
        regionId: bigint;
        dotAmount: bigint;
        xcmHash: string;
        dispatchBlock: bigint;
        confirmBlock: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalSettlements"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "xcmHashToPosition"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  getEvent(
    key: "RecoveryInitiated"
  ): TypedContractEvent<
    RecoveryInitiatedEvent.InputTuple,
    RecoveryInitiatedEvent.OutputTuple,
    RecoveryInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "SettlementConfirmed"
  ): TypedContractEvent<
    SettlementConfirmedEvent.InputTuple,
    SettlementConfirmedEvent.OutputTuple,
    SettlementConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "SettlementDispatched"
  ): TypedContractEvent<
    SettlementDispatchedEvent.InputTuple,
    SettlementDispatchedEvent.OutputTuple,
    SettlementDispatchedEvent.OutputObject
  >;
  getEvent(
    key: "SettlementFailed"
  ): TypedContractEvent<
    SettlementFailedEvent.InputTuple,
    SettlementFailedEvent.OutputTuple,
    SettlementFailedEvent.OutputObject
  >;

  filters: {
    "RecoveryInitiated(uint256,address)": TypedContractEvent<
      RecoveryInitiatedEvent.InputTuple,
      RecoveryInitiatedEvent.OutputTuple,
      RecoveryInitiatedEvent.OutputObject
    >;
    RecoveryInitiated: TypedContractEvent<
      RecoveryInitiatedEvent.InputTuple,
      RecoveryInitiatedEvent.OutputTuple,
      RecoveryInitiatedEvent.OutputObject
    >;

    "SettlementConfirmed(uint256,bytes32)": TypedContractEvent<
      SettlementConfirmedEvent.InputTuple,
      SettlementConfirmedEvent.OutputTuple,
      SettlementConfirmedEvent.OutputObject
    >;
    SettlementConfirmed: TypedContractEvent<
      SettlementConfirmedEvent.InputTuple,
      SettlementConfirmedEvent.OutputTuple,
      SettlementConfirmedEvent.OutputObject
    >;

    "SettlementDispatched(uint256,bytes32)": TypedContractEvent<
      SettlementDispatchedEvent.InputTuple,
      SettlementDispatchedEvent.OutputTuple,
      SettlementDispatchedEvent.OutputObject
    >;
    SettlementDispatched: TypedContractEvent<
      SettlementDispatchedEvent.InputTuple,
      SettlementDispatchedEvent.OutputTuple,
      SettlementDispatchedEvent.OutputObject
    >;

    "SettlementFailed(uint256,bytes32,bytes)": TypedContractEvent<
      SettlementFailedEvent.InputTuple,
      SettlementFailedEvent.OutputTuple,
      SettlementFailedEvent.OutputObject
    >;
    SettlementFailed: TypedContractEvent<
      SettlementFailedEvent.InputTuple,
      SettlementFailedEvent.OutputTuple,
      SettlementFailedEvent.OutputObject
    >;
  };
}
