/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface YieldVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ASSETS_PRECOMPILE"
      | "BASE_RATE"
      | "EPOCH_BLOCKS"
      | "KEY_LEDGER"
      | "RATE_PRECISION"
      | "availableRegions"
      | "borrow"
      | "claimYield"
      | "coretimeNFT"
      | "currentEpoch"
      | "currentEpochFees"
      | "currentLendingRate"
      | "deposit"
      | "depositorReceipts"
      | "deposits"
      | "epochStartBlock"
      | "epochs"
      | "getDepositorReceipts"
      | "loans"
      | "nextLoanId"
      | "nextReceiptId"
      | "regionToReceipt"
      | "registry"
      | "returnLoan"
      | "totalDeposited"
      | "totalLent"
      | "utilisationRate"
      | "withdraw"
      | "yieldClaimed"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RegionDeposited"
      | "RegionLent"
      | "RegionReturned"
      | "RegionWithdrawn"
      | "YieldClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ASSETS_PRECOMPILE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "BASE_RATE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "EPOCH_BLOCKS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "KEY_LEDGER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RATE_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "availableRegions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "borrow",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimYield",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "coretimeNFT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentEpochFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentLendingRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositorReceipts",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "epochStartBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "epochs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositorReceipts",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "nextLoanId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextReceiptId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "regionToReceipt",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "returnLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDeposited",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "totalLent", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "utilisationRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "yieldClaimed",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "ASSETS_PRECOMPILE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BASE_RATE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "EPOCH_BLOCKS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "KEY_LEDGER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "RATE_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "availableRegions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrow", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimYield", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "coretimeNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentEpochFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentLendingRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositorReceipts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "epochStartBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "epochs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDepositorReceipts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextLoanId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextReceiptId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "regionToReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "returnLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalLent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "utilisationRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "yieldClaimed",
    data: BytesLike
  ): Result;
}

export namespace RegionDepositedEvent {
  export type InputTuple = [
    depositor: AddressLike,
    regionId: BigNumberish,
    receiptTokenId: BigNumberish
  ];
  export type OutputTuple = [
    depositor: string,
    regionId: bigint,
    receiptTokenId: bigint
  ];
  export interface OutputObject {
    depositor: string;
    regionId: bigint;
    receiptTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegionLentEvent {
  export type InputTuple = [
    regionId: BigNumberish,
    borrower: AddressLike,
    durationBlocks: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    regionId: bigint,
    borrower: string,
    durationBlocks: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    regionId: bigint;
    borrower: string;
    durationBlocks: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegionReturnedEvent {
  export type InputTuple = [regionId: BigNumberish];
  export type OutputTuple = [regionId: bigint];
  export interface OutputObject {
    regionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegionWithdrawnEvent {
  export type InputTuple = [depositor: AddressLike, regionId: BigNumberish];
  export type OutputTuple = [depositor: string, regionId: bigint];
  export interface OutputObject {
    depositor: string;
    regionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldClaimedEvent {
  export type InputTuple = [
    depositor: AddressLike,
    receiptTokenId: BigNumberish,
    amountDOT: BigNumberish
  ];
  export type OutputTuple = [
    depositor: string,
    receiptTokenId: bigint,
    amountDOT: bigint
  ];
  export interface OutputObject {
    depositor: string;
    receiptTokenId: bigint;
    amountDOT: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface YieldVault extends BaseContract {
  connect(runner?: ContractRunner | null): YieldVault;
  waitForDeployment(): Promise<this>;

  interface: YieldVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ASSETS_PRECOMPILE: TypedContractMethod<[], [string], "view">;

  BASE_RATE: TypedContractMethod<[], [bigint], "view">;

  EPOCH_BLOCKS: TypedContractMethod<[], [bigint], "view">;

  KEY_LEDGER: TypedContractMethod<[], [string], "view">;

  RATE_PRECISION: TypedContractMethod<[], [bigint], "view">;

  availableRegions: TypedContractMethod<[], [bigint], "view">;

  borrow: TypedContractMethod<
    [coreCount: BigNumberish, durationBlocks: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  claimYield: TypedContractMethod<
    [receiptTokenId: BigNumberish, epoch: BigNumberish],
    [void],
    "nonpayable"
  >;

  coretimeNFT: TypedContractMethod<[], [string], "view">;

  currentEpoch: TypedContractMethod<[], [bigint], "view">;

  currentEpochFees: TypedContractMethod<[], [bigint], "view">;

  currentLendingRate: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<
    [regionId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  depositorReceipts: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  deposits: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean, boolean] & {
        receiptTokenId: bigint;
        depositor: string;
        regionId: bigint;
        depositBlock: bigint;
        isLent: boolean;
        withdrawn: boolean;
      }
    ],
    "view"
  >;

  epochStartBlock: TypedContractMethod<[], [bigint], "view">;

  epochs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        totalFeesCollected: bigint;
        activeDepositCount: bigint;
        finalized: boolean;
      }
    ],
    "view"
  >;

  getDepositorReceipts: TypedContractMethod<
    [depositor: AddressLike],
    [bigint[]],
    "view"
  >;

  loans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, boolean] & {
        loanId: bigint;
        borrower: string;
        regionId: bigint;
        startBlock: bigint;
        durationBlocks: bigint;
        feePaid: bigint;
        returned: boolean;
      }
    ],
    "view"
  >;

  nextLoanId: TypedContractMethod<[], [bigint], "view">;

  nextReceiptId: TypedContractMethod<[], [bigint], "view">;

  regionToReceipt: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  returnLoan: TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;

  totalDeposited: TypedContractMethod<[], [bigint], "view">;

  totalLent: TypedContractMethod<[], [bigint], "view">;

  utilisationRate: TypedContractMethod<[], [bigint], "view">;

  withdraw: TypedContractMethod<
    [receiptTokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  yieldClaimed: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ASSETS_PRECOMPILE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BASE_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "EPOCH_BLOCKS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "KEY_LEDGER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RATE_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "availableRegions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "borrow"
  ): TypedContractMethod<
    [coreCount: BigNumberish, durationBlocks: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimYield"
  ): TypedContractMethod<
    [receiptTokenId: BigNumberish, epoch: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "coretimeNFT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "currentEpoch"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentEpochFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentLendingRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[regionId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "depositorReceipts"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposits"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, boolean, boolean] & {
        receiptTokenId: bigint;
        depositor: string;
        regionId: bigint;
        depositBlock: bigint;
        isLent: boolean;
        withdrawn: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "epochStartBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "epochs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        totalFeesCollected: bigint;
        activeDepositCount: bigint;
        finalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDepositorReceipts"
  ): TypedContractMethod<[depositor: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, boolean] & {
        loanId: bigint;
        borrower: string;
        regionId: bigint;
        startBlock: bigint;
        durationBlocks: bigint;
        feePaid: bigint;
        returned: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextLoanId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextReceiptId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "regionToReceipt"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "returnLoan"
  ): TypedContractMethod<[loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalDeposited"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalLent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "utilisationRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[receiptTokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "yieldClaimed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  getEvent(
    key: "RegionDeposited"
  ): TypedContractEvent<
    RegionDepositedEvent.InputTuple,
    RegionDepositedEvent.OutputTuple,
    RegionDepositedEvent.OutputObject
  >;
  getEvent(
    key: "RegionLent"
  ): TypedContractEvent<
    RegionLentEvent.InputTuple,
    RegionLentEvent.OutputTuple,
    RegionLentEvent.OutputObject
  >;
  getEvent(
    key: "RegionReturned"
  ): TypedContractEvent<
    RegionReturnedEvent.InputTuple,
    RegionReturnedEvent.OutputTuple,
    RegionReturnedEvent.OutputObject
  >;
  getEvent(
    key: "RegionWithdrawn"
  ): TypedContractEvent<
    RegionWithdrawnEvent.InputTuple,
    RegionWithdrawnEvent.OutputTuple,
    RegionWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "YieldClaimed"
  ): TypedContractEvent<
    YieldClaimedEvent.InputTuple,
    YieldClaimedEvent.OutputTuple,
    YieldClaimedEvent.OutputObject
  >;

  filters: {
    "RegionDeposited(address,uint128,uint256)": TypedContractEvent<
      RegionDepositedEvent.InputTuple,
      RegionDepositedEvent.OutputTuple,
      RegionDepositedEvent.OutputObject
    >;
    RegionDeposited: TypedContractEvent<
      RegionDepositedEvent.InputTuple,
      RegionDepositedEvent.OutputTuple,
      RegionDepositedEvent.OutputObject
    >;

    "RegionLent(uint128,address,uint32,uint128)": TypedContractEvent<
      RegionLentEvent.InputTuple,
      RegionLentEvent.OutputTuple,
      RegionLentEvent.OutputObject
    >;
    RegionLent: TypedContractEvent<
      RegionLentEvent.InputTuple,
      RegionLentEvent.OutputTuple,
      RegionLentEvent.OutputObject
    >;

    "RegionReturned(uint128)": TypedContractEvent<
      RegionReturnedEvent.InputTuple,
      RegionReturnedEvent.OutputTuple,
      RegionReturnedEvent.OutputObject
    >;
    RegionReturned: TypedContractEvent<
      RegionReturnedEvent.InputTuple,
      RegionReturnedEvent.OutputTuple,
      RegionReturnedEvent.OutputObject
    >;

    "RegionWithdrawn(address,uint128)": TypedContractEvent<
      RegionWithdrawnEvent.InputTuple,
      RegionWithdrawnEvent.OutputTuple,
      RegionWithdrawnEvent.OutputObject
    >;
    RegionWithdrawn: TypedContractEvent<
      RegionWithdrawnEvent.InputTuple,
      RegionWithdrawnEvent.OutputTuple,
      RegionWithdrawnEvent.OutputObject
    >;

    "YieldClaimed(address,uint256,uint128)": TypedContractEvent<
      YieldClaimedEvent.InputTuple,
      YieldClaimedEvent.OutputTuple,
      YieldClaimedEvent.OutputObject
    >;
    YieldClaimed: TypedContractEvent<
      YieldClaimedEvent.InputTuple,
      YieldClaimedEvent.OutputTuple,
      YieldClaimedEvent.OutputObject
    >;
  };
}
