/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { Errors, ErrorsInterface } from "../../libraries/Errors";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "positionId",
        type: "uint256",
      },
    ],
    name: "AlreadySettled",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "key",
        type: "bytes32",
      },
    ],
    name: "ContractNotFound",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "DOTTransferFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "deliveryBlock",
        type: "uint32",
      },
    ],
    name: "DeliveryBlockInPast",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "deliveryBlock",
        type: "uint32",
      },
    ],
    name: "DeliveryBlockNotReached",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "coreCount",
        type: "uint32",
      },
    ],
    name: "InsufficientLiquidity",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "receiptTokenId",
        type: "uint256",
      },
    ],
    name: "InvalidReceiptToken",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "loanId",
        type: "uint256",
      },
    ],
    name: "LoanAlreadyReturned",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "loanId",
        type: "uint256",
      },
    ],
    name: "LoanNotExpired",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "regionId",
        type: "uint128",
      },
    ],
    name: "NFTTransferFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "optionId",
        type: "uint256",
      },
      {
        internalType: "uint32",
        name: "expiryBlock",
        type: "uint32",
      },
    ],
    name: "NotAtExpiryBlock",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "optionId",
        type: "uint256",
      },
    ],
    name: "NotOptionHolder",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
    ],
    name: "NotOrderParty",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "optionId",
        type: "uint256",
      },
    ],
    name: "OptionAlreadyExpired",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "optionId",
        type: "uint256",
      },
    ],
    name: "OptionNotActive",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "optionId",
        type: "uint256",
      },
    ],
    name: "OptionNotExpired",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
    ],
    name: "OrderAlreadyFinalized",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
    ],
    name: "OrderNotFound",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
    ],
    name: "OrderNotMatched",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "orderId",
        type: "uint256",
      },
    ],
    name: "OrderNotOpen",
    type: "error",
  },
  {
    inputs: [],
    name: "PricingModuleCallFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "ProtocolPaused",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "positionId",
        type: "uint256",
      },
    ],
    name: "RecoveryTimeoutNotReached",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "regionId",
        type: "uint128",
      },
    ],
    name: "RegionAlreadyEncumbered",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "regionId",
        type: "uint128",
      },
    ],
    name: "RegionCurrentlyLent",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "positionId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "xcmHash",
        type: "bytes32",
      },
    ],
    name: "SettlementCallbackFailed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint128",
        name: "strike",
        type: "uint128",
      },
      {
        internalType: "uint128",
        name: "spot",
        type: "uint128",
      },
    ],
    name: "StrikePriceOutOfBand",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "key",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "activationBlock",
        type: "uint256",
      },
    ],
    name: "TimelockNotExpired",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
    ],
    name: "Unauthorised",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        internalType: "address",
        name: "expected",
        type: "address",
      },
    ],
    name: "UnauthorisedCaller",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "xcmHash",
        type: "bytes32",
      },
    ],
    name: "XcmDispatchFailed",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAddress",
    type: "error",
  },
  {
    inputs: [],
    name: "ZeroAmount",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220d841aedf69e8d6e2e3aff33860098fb1e828a9e14be94c9f449459ee03d2335164736f6c63430008140033";

type ErrorsConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ErrorsConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Errors__factory extends ContractFactory {
  constructor(...args: ErrorsConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Errors & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Errors__factory {
    return super.connect(runner) as Errors__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ErrorsInterface {
    return new Interface(_abi) as ErrorsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Errors {
    return new Contract(address, _abi, runner) as unknown as Errors;
  }
}
