/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAssetsPrecompile } from "./IAssetsPrecompile";
export type { ICoreDexRegistry } from "./ICoreDexRegistry";
export type { ICoretimeNFT } from "./ICoretimeNFT";
export type { IXcmPrecompile } from "./IXcmPrecompile";
