/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IXcmPrecompile {
  export type WeightStruct = { refTime: BigNumberish; proofSize: BigNumberish };

  export type WeightStructOutput = [refTime: bigint, proofSize: bigint] & {
    refTime: bigint;
    proofSize: bigint;
  };

  export type OutcomeStruct = { success: boolean; error: BytesLike };

  export type OutcomeStructOutput = [success: boolean, error: string] & {
    success: boolean;
    error: string;
  };
}

export interface IXcmPrecompileInterface extends Interface {
  getFunction(
    nameOrSignature: "execute" | "remoteTransact" | "sendXcm" | "teleportDOT"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "execute",
    values: [BytesLike, IXcmPrecompile.WeightStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "remoteTransact",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sendXcm",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "teleportDOT",
    values: [BigNumberish, AddressLike, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "remoteTransact",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sendXcm", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "teleportDOT",
    data: BytesLike
  ): Result;
}

export interface IXcmPrecompile extends BaseContract {
  connect(runner?: ContractRunner | null): IXcmPrecompile;
  waitForDeployment(): Promise<this>;

  interface: IXcmPrecompileInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  execute: TypedContractMethod<
    [xcmProgram: BytesLike, maxWeight: IXcmPrecompile.WeightStruct],
    [IXcmPrecompile.OutcomeStructOutput],
    "nonpayable"
  >;

  remoteTransact: TypedContractMethod<
    [
      destinationParaId: BigNumberish,
      call: BytesLike,
      weightLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  sendXcm: TypedContractMethod<
    [dest: BytesLike, xcmProgram: BytesLike],
    [string],
    "nonpayable"
  >;

  teleportDOT: TypedContractMethod<
    [
      destinationParaId: BigNumberish,
      beneficiary: AddressLike,
      amount: BigNumberish,
      weightLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<
    [xcmProgram: BytesLike, maxWeight: IXcmPrecompile.WeightStruct],
    [IXcmPrecompile.OutcomeStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remoteTransact"
  ): TypedContractMethod<
    [
      destinationParaId: BigNumberish,
      call: BytesLike,
      weightLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendXcm"
  ): TypedContractMethod<
    [dest: BytesLike, xcmProgram: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "teleportDOT"
  ): TypedContractMethod<
    [
      destinationParaId: BigNumberish,
      beneficiary: AddressLike,
      amount: BigNumberish,
      weightLimit: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
