/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IXcmPrecompile,
  IXcmPrecompileInterface,
} from "../../interfaces/IXcmPrecompile";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
      {
        internalType: "uint64",
        name: "maxWeight",
        type: "uint64",
      },
    ],
    name: "execute",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "dest",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "send",
    outputs: [
      {
        internalType: "bytes32",
        name: "messageId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "weighMessage",
    outputs: [
      {
        internalType: "uint64",
        name: "weight",
        type: "uint64",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IXcmPrecompile__factory {
  static readonly abi = _abi;
  static createInterface(): IXcmPrecompileInterface {
    return new Interface(_abi) as IXcmPrecompileInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IXcmPrecompile {
    return new Contract(address, _abi, runner) as unknown as IXcmPrecompile;
  }
}
