/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IXcmPrecompile,
  IXcmPrecompileInterface,
} from "../../interfaces/IXcmPrecompile";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "xcmProgram",
        type: "bytes",
      },
      {
        components: [
          {
            internalType: "uint64",
            name: "refTime",
            type: "uint64",
          },
          {
            internalType: "uint64",
            name: "proofSize",
            type: "uint64",
          },
        ],
        internalType: "struct IXcmPrecompile.Weight",
        name: "maxWeight",
        type: "tuple",
      },
    ],
    name: "execute",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "success",
            type: "bool",
          },
          {
            internalType: "bytes",
            name: "error",
            type: "bytes",
          },
        ],
        internalType: "struct IXcmPrecompile.Outcome",
        name: "outcome",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "destinationParaId",
        type: "uint32",
      },
      {
        internalType: "bytes",
        name: "call",
        type: "bytes",
      },
      {
        internalType: "uint64",
        name: "weightLimit",
        type: "uint64",
      },
    ],
    name: "remoteTransact",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "dest",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "xcmProgram",
        type: "bytes",
      },
    ],
    name: "sendXcm",
    outputs: [
      {
        internalType: "bytes32",
        name: "messageHash",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "destinationParaId",
        type: "uint32",
      },
      {
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint64",
        name: "weightLimit",
        type: "uint64",
      },
    ],
    name: "teleportDOT",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IXcmPrecompile__factory {
  static readonly abi = _abi;
  static createInterface(): IXcmPrecompileInterface {
    return new Interface(_abi) as IXcmPrecompileInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IXcmPrecompile {
    return new Contract(address, _abi, runner) as unknown as IXcmPrecompile;
  }
}
