/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../common";

export interface EventsInterface extends Interface {
  getEvent(
    nameOrSignatureOrTopic:
      | "ContractUpdated"
      | "MarginUpdated"
      | "OptionExercised"
      | "OptionExpired"
      | "OptionPurchased"
      | "OptionWritten"
      | "OrderCancelled"
      | "OrderCreated"
      | "OrderExpired"
      | "OrderMatched"
      | "OrderSettled"
      | "ProtocolPaused"
      | "ProtocolUnpaused"
      | "RecoveryInitiated"
      | "RegionDeposited"
      | "RegionLent"
      | "RegionLocked"
      | "RegionReturned"
      | "RegionUnlocked"
      | "RegionWithdrawn"
      | "SettlementConfirmed"
      | "SettlementDispatched"
      | "SettlementFailed"
      | "YieldClaimed"
  ): EventFragment;
}

export namespace ContractUpdatedEvent {
  export type InputTuple = [
    key: BytesLike,
    oldAddress: AddressLike,
    newAddress: AddressLike,
    version: BigNumberish
  ];
  export type OutputTuple = [
    key: string,
    oldAddress: string,
    newAddress: string,
    version: bigint
  ];
  export interface OutputObject {
    key: string;
    oldAddress: string;
    newAddress: string;
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarginUpdatedEvent {
  export type InputTuple = [account: AddressLike, newBalance: BigNumberish];
  export type OutputTuple = [account: string, newBalance: bigint];
  export interface OutputObject {
    account: string;
    newBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OptionExercisedEvent {
  export type InputTuple = [optionId: BigNumberish, holder: AddressLike];
  export type OutputTuple = [optionId: bigint, holder: string];
  export interface OutputObject {
    optionId: bigint;
    holder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OptionExpiredEvent {
  export type InputTuple = [optionId: BigNumberish];
  export type OutputTuple = [optionId: bigint];
  export interface OutputObject {
    optionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OptionPurchasedEvent {
  export type InputTuple = [optionId: BigNumberish, holder: AddressLike];
  export type OutputTuple = [optionId: bigint, holder: string];
  export interface OutputObject {
    optionId: bigint;
    holder: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OptionWrittenEvent {
  export type InputTuple = [
    optionId: BigNumberish,
    writer: AddressLike,
    optionType: BigNumberish,
    premium: BigNumberish
  ];
  export type OutputTuple = [
    optionId: bigint,
    writer: string,
    optionType: bigint,
    premium: bigint
  ];
  export interface OutputObject {
    optionId: bigint;
    writer: string;
    optionType: bigint;
    premium: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCancelledEvent {
  export type InputTuple = [orderId: BigNumberish, cancelledBy: AddressLike];
  export type OutputTuple = [orderId: bigint, cancelledBy: string];
  export interface OutputObject {
    orderId: bigint;
    cancelledBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderCreatedEvent {
  export type InputTuple = [
    orderId: BigNumberish,
    seller: AddressLike,
    regionId: BigNumberish,
    strikePriceDOT: BigNumberish,
    deliveryBlock: BigNumberish
  ];
  export type OutputTuple = [
    orderId: bigint,
    seller: string,
    regionId: bigint,
    strikePriceDOT: bigint,
    deliveryBlock: bigint
  ];
  export interface OutputObject {
    orderId: bigint;
    seller: string;
    regionId: bigint;
    strikePriceDOT: bigint;
    deliveryBlock: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderExpiredEvent {
  export type InputTuple = [orderId: BigNumberish];
  export type OutputTuple = [orderId: bigint];
  export interface OutputObject {
    orderId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderMatchedEvent {
  export type InputTuple = [orderId: BigNumberish, buyer: AddressLike];
  export type OutputTuple = [orderId: bigint, buyer: string];
  export interface OutputObject {
    orderId: bigint;
    buyer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OrderSettledEvent {
  export type InputTuple = [orderId: BigNumberish, success: boolean];
  export type OutputTuple = [orderId: bigint, success: boolean];
  export interface OutputObject {
    orderId: bigint;
    success: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolPausedEvent {
  export type InputTuple = [pauser: AddressLike];
  export type OutputTuple = [pauser: string];
  export interface OutputObject {
    pauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolUnpausedEvent {
  export type InputTuple = [unpauser: AddressLike];
  export type OutputTuple = [unpauser: string];
  export interface OutputObject {
    unpauser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoveryInitiatedEvent {
  export type InputTuple = [positionId: BigNumberish, initiator: AddressLike];
  export type OutputTuple = [positionId: bigint, initiator: string];
  export interface OutputObject {
    positionId: bigint;
    initiator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegionDepositedEvent {
  export type InputTuple = [
    depositor: AddressLike,
    regionId: BigNumberish,
    receiptTokenId: BigNumberish
  ];
  export type OutputTuple = [
    depositor: string,
    regionId: bigint,
    receiptTokenId: bigint
  ];
  export interface OutputObject {
    depositor: string;
    regionId: bigint;
    receiptTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegionLentEvent {
  export type InputTuple = [
    regionId: BigNumberish,
    borrower: AddressLike,
    durationBlocks: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    regionId: bigint,
    borrower: string,
    durationBlocks: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    regionId: bigint;
    borrower: string;
    durationBlocks: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegionLockedEvent {
  export type InputTuple = [
    regionId: BigNumberish,
    lockedBy: AddressLike,
    positionType: BytesLike
  ];
  export type OutputTuple = [
    regionId: bigint,
    lockedBy: string,
    positionType: string
  ];
  export interface OutputObject {
    regionId: bigint;
    lockedBy: string;
    positionType: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegionReturnedEvent {
  export type InputTuple = [regionId: BigNumberish];
  export type OutputTuple = [regionId: bigint];
  export interface OutputObject {
    regionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegionUnlockedEvent {
  export type InputTuple = [regionId: BigNumberish, unlockedBy: AddressLike];
  export type OutputTuple = [regionId: bigint, unlockedBy: string];
  export interface OutputObject {
    regionId: bigint;
    unlockedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegionWithdrawnEvent {
  export type InputTuple = [depositor: AddressLike, regionId: BigNumberish];
  export type OutputTuple = [depositor: string, regionId: bigint];
  export interface OutputObject {
    depositor: string;
    regionId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementConfirmedEvent {
  export type InputTuple = [positionId: BigNumberish, xcmHash: BytesLike];
  export type OutputTuple = [positionId: bigint, xcmHash: string];
  export interface OutputObject {
    positionId: bigint;
    xcmHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementDispatchedEvent {
  export type InputTuple = [positionId: BigNumberish, xcmHash: BytesLike];
  export type OutputTuple = [positionId: bigint, xcmHash: string];
  export interface OutputObject {
    positionId: bigint;
    xcmHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementFailedEvent {
  export type InputTuple = [
    positionId: BigNumberish,
    xcmHash: BytesLike,
    reason: BytesLike
  ];
  export type OutputTuple = [
    positionId: bigint,
    xcmHash: string,
    reason: string
  ];
  export interface OutputObject {
    positionId: bigint;
    xcmHash: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldClaimedEvent {
  export type InputTuple = [
    depositor: AddressLike,
    receiptTokenId: BigNumberish,
    amountDOT: BigNumberish
  ];
  export type OutputTuple = [
    depositor: string,
    receiptTokenId: bigint,
    amountDOT: bigint
  ];
  export interface OutputObject {
    depositor: string;
    receiptTokenId: bigint;
    amountDOT: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Events extends BaseContract {
  connect(runner?: ContractRunner | null): Events;
  waitForDeployment(): Promise<this>;

  interface: EventsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "ContractUpdated"
  ): TypedContractEvent<
    ContractUpdatedEvent.InputTuple,
    ContractUpdatedEvent.OutputTuple,
    ContractUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MarginUpdated"
  ): TypedContractEvent<
    MarginUpdatedEvent.InputTuple,
    MarginUpdatedEvent.OutputTuple,
    MarginUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OptionExercised"
  ): TypedContractEvent<
    OptionExercisedEvent.InputTuple,
    OptionExercisedEvent.OutputTuple,
    OptionExercisedEvent.OutputObject
  >;
  getEvent(
    key: "OptionExpired"
  ): TypedContractEvent<
    OptionExpiredEvent.InputTuple,
    OptionExpiredEvent.OutputTuple,
    OptionExpiredEvent.OutputObject
  >;
  getEvent(
    key: "OptionPurchased"
  ): TypedContractEvent<
    OptionPurchasedEvent.InputTuple,
    OptionPurchasedEvent.OutputTuple,
    OptionPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "OptionWritten"
  ): TypedContractEvent<
    OptionWrittenEvent.InputTuple,
    OptionWrittenEvent.OutputTuple,
    OptionWrittenEvent.OutputObject
  >;
  getEvent(
    key: "OrderCancelled"
  ): TypedContractEvent<
    OrderCancelledEvent.InputTuple,
    OrderCancelledEvent.OutputTuple,
    OrderCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OrderCreated"
  ): TypedContractEvent<
    OrderCreatedEvent.InputTuple,
    OrderCreatedEvent.OutputTuple,
    OrderCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OrderExpired"
  ): TypedContractEvent<
    OrderExpiredEvent.InputTuple,
    OrderExpiredEvent.OutputTuple,
    OrderExpiredEvent.OutputObject
  >;
  getEvent(
    key: "OrderMatched"
  ): TypedContractEvent<
    OrderMatchedEvent.InputTuple,
    OrderMatchedEvent.OutputTuple,
    OrderMatchedEvent.OutputObject
  >;
  getEvent(
    key: "OrderSettled"
  ): TypedContractEvent<
    OrderSettledEvent.InputTuple,
    OrderSettledEvent.OutputTuple,
    OrderSettledEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolPaused"
  ): TypedContractEvent<
    ProtocolPausedEvent.InputTuple,
    ProtocolPausedEvent.OutputTuple,
    ProtocolPausedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolUnpaused"
  ): TypedContractEvent<
    ProtocolUnpausedEvent.InputTuple,
    ProtocolUnpausedEvent.OutputTuple,
    ProtocolUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "RecoveryInitiated"
  ): TypedContractEvent<
    RecoveryInitiatedEvent.InputTuple,
    RecoveryInitiatedEvent.OutputTuple,
    RecoveryInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "RegionDeposited"
  ): TypedContractEvent<
    RegionDepositedEvent.InputTuple,
    RegionDepositedEvent.OutputTuple,
    RegionDepositedEvent.OutputObject
  >;
  getEvent(
    key: "RegionLent"
  ): TypedContractEvent<
    RegionLentEvent.InputTuple,
    RegionLentEvent.OutputTuple,
    RegionLentEvent.OutputObject
  >;
  getEvent(
    key: "RegionLocked"
  ): TypedContractEvent<
    RegionLockedEvent.InputTuple,
    RegionLockedEvent.OutputTuple,
    RegionLockedEvent.OutputObject
  >;
  getEvent(
    key: "RegionReturned"
  ): TypedContractEvent<
    RegionReturnedEvent.InputTuple,
    RegionReturnedEvent.OutputTuple,
    RegionReturnedEvent.OutputObject
  >;
  getEvent(
    key: "RegionUnlocked"
  ): TypedContractEvent<
    RegionUnlockedEvent.InputTuple,
    RegionUnlockedEvent.OutputTuple,
    RegionUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "RegionWithdrawn"
  ): TypedContractEvent<
    RegionWithdrawnEvent.InputTuple,
    RegionWithdrawnEvent.OutputTuple,
    RegionWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "SettlementConfirmed"
  ): TypedContractEvent<
    SettlementConfirmedEvent.InputTuple,
    SettlementConfirmedEvent.OutputTuple,
    SettlementConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "SettlementDispatched"
  ): TypedContractEvent<
    SettlementDispatchedEvent.InputTuple,
    SettlementDispatchedEvent.OutputTuple,
    SettlementDispatchedEvent.OutputObject
  >;
  getEvent(
    key: "SettlementFailed"
  ): TypedContractEvent<
    SettlementFailedEvent.InputTuple,
    SettlementFailedEvent.OutputTuple,
    SettlementFailedEvent.OutputObject
  >;
  getEvent(
    key: "YieldClaimed"
  ): TypedContractEvent<
    YieldClaimedEvent.InputTuple,
    YieldClaimedEvent.OutputTuple,
    YieldClaimedEvent.OutputObject
  >;

  filters: {
    "ContractUpdated(bytes32,address,address,uint32)": TypedContractEvent<
      ContractUpdatedEvent.InputTuple,
      ContractUpdatedEvent.OutputTuple,
      ContractUpdatedEvent.OutputObject
    >;
    ContractUpdated: TypedContractEvent<
      ContractUpdatedEvent.InputTuple,
      ContractUpdatedEvent.OutputTuple,
      ContractUpdatedEvent.OutputObject
    >;

    "MarginUpdated(address,uint256)": TypedContractEvent<
      MarginUpdatedEvent.InputTuple,
      MarginUpdatedEvent.OutputTuple,
      MarginUpdatedEvent.OutputObject
    >;
    MarginUpdated: TypedContractEvent<
      MarginUpdatedEvent.InputTuple,
      MarginUpdatedEvent.OutputTuple,
      MarginUpdatedEvent.OutputObject
    >;

    "OptionExercised(uint256,address)": TypedContractEvent<
      OptionExercisedEvent.InputTuple,
      OptionExercisedEvent.OutputTuple,
      OptionExercisedEvent.OutputObject
    >;
    OptionExercised: TypedContractEvent<
      OptionExercisedEvent.InputTuple,
      OptionExercisedEvent.OutputTuple,
      OptionExercisedEvent.OutputObject
    >;

    "OptionExpired(uint256)": TypedContractEvent<
      OptionExpiredEvent.InputTuple,
      OptionExpiredEvent.OutputTuple,
      OptionExpiredEvent.OutputObject
    >;
    OptionExpired: TypedContractEvent<
      OptionExpiredEvent.InputTuple,
      OptionExpiredEvent.OutputTuple,
      OptionExpiredEvent.OutputObject
    >;

    "OptionPurchased(uint256,address)": TypedContractEvent<
      OptionPurchasedEvent.InputTuple,
      OptionPurchasedEvent.OutputTuple,
      OptionPurchasedEvent.OutputObject
    >;
    OptionPurchased: TypedContractEvent<
      OptionPurchasedEvent.InputTuple,
      OptionPurchasedEvent.OutputTuple,
      OptionPurchasedEvent.OutputObject
    >;

    "OptionWritten(uint256,address,uint8,uint128)": TypedContractEvent<
      OptionWrittenEvent.InputTuple,
      OptionWrittenEvent.OutputTuple,
      OptionWrittenEvent.OutputObject
    >;
    OptionWritten: TypedContractEvent<
      OptionWrittenEvent.InputTuple,
      OptionWrittenEvent.OutputTuple,
      OptionWrittenEvent.OutputObject
    >;

    "OrderCancelled(uint256,address)": TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;
    OrderCancelled: TypedContractEvent<
      OrderCancelledEvent.InputTuple,
      OrderCancelledEvent.OutputTuple,
      OrderCancelledEvent.OutputObject
    >;

    "OrderCreated(uint256,address,uint128,uint128,uint32)": TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;
    OrderCreated: TypedContractEvent<
      OrderCreatedEvent.InputTuple,
      OrderCreatedEvent.OutputTuple,
      OrderCreatedEvent.OutputObject
    >;

    "OrderExpired(uint256)": TypedContractEvent<
      OrderExpiredEvent.InputTuple,
      OrderExpiredEvent.OutputTuple,
      OrderExpiredEvent.OutputObject
    >;
    OrderExpired: TypedContractEvent<
      OrderExpiredEvent.InputTuple,
      OrderExpiredEvent.OutputTuple,
      OrderExpiredEvent.OutputObject
    >;

    "OrderMatched(uint256,address)": TypedContractEvent<
      OrderMatchedEvent.InputTuple,
      OrderMatchedEvent.OutputTuple,
      OrderMatchedEvent.OutputObject
    >;
    OrderMatched: TypedContractEvent<
      OrderMatchedEvent.InputTuple,
      OrderMatchedEvent.OutputTuple,
      OrderMatchedEvent.OutputObject
    >;

    "OrderSettled(uint256,bool)": TypedContractEvent<
      OrderSettledEvent.InputTuple,
      OrderSettledEvent.OutputTuple,
      OrderSettledEvent.OutputObject
    >;
    OrderSettled: TypedContractEvent<
      OrderSettledEvent.InputTuple,
      OrderSettledEvent.OutputTuple,
      OrderSettledEvent.OutputObject
    >;

    "ProtocolPaused(address)": TypedContractEvent<
      ProtocolPausedEvent.InputTuple,
      ProtocolPausedEvent.OutputTuple,
      ProtocolPausedEvent.OutputObject
    >;
    ProtocolPaused: TypedContractEvent<
      ProtocolPausedEvent.InputTuple,
      ProtocolPausedEvent.OutputTuple,
      ProtocolPausedEvent.OutputObject
    >;

    "ProtocolUnpaused(address)": TypedContractEvent<
      ProtocolUnpausedEvent.InputTuple,
      ProtocolUnpausedEvent.OutputTuple,
      ProtocolUnpausedEvent.OutputObject
    >;
    ProtocolUnpaused: TypedContractEvent<
      ProtocolUnpausedEvent.InputTuple,
      ProtocolUnpausedEvent.OutputTuple,
      ProtocolUnpausedEvent.OutputObject
    >;

    "RecoveryInitiated(uint256,address)": TypedContractEvent<
      RecoveryInitiatedEvent.InputTuple,
      RecoveryInitiatedEvent.OutputTuple,
      RecoveryInitiatedEvent.OutputObject
    >;
    RecoveryInitiated: TypedContractEvent<
      RecoveryInitiatedEvent.InputTuple,
      RecoveryInitiatedEvent.OutputTuple,
      RecoveryInitiatedEvent.OutputObject
    >;

    "RegionDeposited(address,uint128,uint256)": TypedContractEvent<
      RegionDepositedEvent.InputTuple,
      RegionDepositedEvent.OutputTuple,
      RegionDepositedEvent.OutputObject
    >;
    RegionDeposited: TypedContractEvent<
      RegionDepositedEvent.InputTuple,
      RegionDepositedEvent.OutputTuple,
      RegionDepositedEvent.OutputObject
    >;

    "RegionLent(uint128,address,uint32,uint128)": TypedContractEvent<
      RegionLentEvent.InputTuple,
      RegionLentEvent.OutputTuple,
      RegionLentEvent.OutputObject
    >;
    RegionLent: TypedContractEvent<
      RegionLentEvent.InputTuple,
      RegionLentEvent.OutputTuple,
      RegionLentEvent.OutputObject
    >;

    "RegionLocked(uint128,address,bytes32)": TypedContractEvent<
      RegionLockedEvent.InputTuple,
      RegionLockedEvent.OutputTuple,
      RegionLockedEvent.OutputObject
    >;
    RegionLocked: TypedContractEvent<
      RegionLockedEvent.InputTuple,
      RegionLockedEvent.OutputTuple,
      RegionLockedEvent.OutputObject
    >;

    "RegionReturned(uint128)": TypedContractEvent<
      RegionReturnedEvent.InputTuple,
      RegionReturnedEvent.OutputTuple,
      RegionReturnedEvent.OutputObject
    >;
    RegionReturned: TypedContractEvent<
      RegionReturnedEvent.InputTuple,
      RegionReturnedEvent.OutputTuple,
      RegionReturnedEvent.OutputObject
    >;

    "RegionUnlocked(uint128,address)": TypedContractEvent<
      RegionUnlockedEvent.InputTuple,
      RegionUnlockedEvent.OutputTuple,
      RegionUnlockedEvent.OutputObject
    >;
    RegionUnlocked: TypedContractEvent<
      RegionUnlockedEvent.InputTuple,
      RegionUnlockedEvent.OutputTuple,
      RegionUnlockedEvent.OutputObject
    >;

    "RegionWithdrawn(address,uint128)": TypedContractEvent<
      RegionWithdrawnEvent.InputTuple,
      RegionWithdrawnEvent.OutputTuple,
      RegionWithdrawnEvent.OutputObject
    >;
    RegionWithdrawn: TypedContractEvent<
      RegionWithdrawnEvent.InputTuple,
      RegionWithdrawnEvent.OutputTuple,
      RegionWithdrawnEvent.OutputObject
    >;

    "SettlementConfirmed(uint256,bytes32)": TypedContractEvent<
      SettlementConfirmedEvent.InputTuple,
      SettlementConfirmedEvent.OutputTuple,
      SettlementConfirmedEvent.OutputObject
    >;
    SettlementConfirmed: TypedContractEvent<
      SettlementConfirmedEvent.InputTuple,
      SettlementConfirmedEvent.OutputTuple,
      SettlementConfirmedEvent.OutputObject
    >;

    "SettlementDispatched(uint256,bytes32)": TypedContractEvent<
      SettlementDispatchedEvent.InputTuple,
      SettlementDispatchedEvent.OutputTuple,
      SettlementDispatchedEvent.OutputObject
    >;
    SettlementDispatched: TypedContractEvent<
      SettlementDispatchedEvent.InputTuple,
      SettlementDispatchedEvent.OutputTuple,
      SettlementDispatchedEvent.OutputObject
    >;

    "SettlementFailed(uint256,bytes32,bytes)": TypedContractEvent<
      SettlementFailedEvent.InputTuple,
      SettlementFailedEvent.OutputTuple,
      SettlementFailedEvent.OutputObject
    >;
    SettlementFailed: TypedContractEvent<
      SettlementFailedEvent.InputTuple,
      SettlementFailedEvent.OutputTuple,
      SettlementFailedEvent.OutputObject
    >;

    "YieldClaimed(address,uint256,uint128)": TypedContractEvent<
      YieldClaimedEvent.InputTuple,
      YieldClaimedEvent.OutputTuple,
      YieldClaimedEvent.OutputObject
    >;
    YieldClaimed: TypedContractEvent<
      YieldClaimedEvent.InputTuple,
      YieldClaimedEvent.OutputTuple,
      YieldClaimedEvent.OutputObject
    >;
  };
}
